

version: '3.1'

services:

  java:
    image: openjdk:11-jre-slim
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - java
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongo

  mongo:
    image: mongo:4.1.6
    expose:
      - "27018"
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin.4238844
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin.4238844
    volumes:
      - /media/storage/masterchef/mongodb:/data/db
