version: '3.1'

services:

  java:
    image: openjdk:8-jdk-alpine
  api_service:
    build: .
    restart: always
    ports:
      - 8181:8181
    links:
      - java
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongo
