version: '3.1'

services:

  java:
    image: openjdk:8-jdk-alpine
  api_service:
    build: .
    restart: always
    ports:
      - 8282:8282
    links:
      - java
    networks:
      - ctnr-net
    volumes:
      - /media/storage/masterchef/
networks:
  ctnr-net:
    external: true
